services:
  db:
    image: postgres:17
    container_name: postgres_compose
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db-volume:/var/lib/postgres/data
    networks:
      - my_network_compose

  app:
    build: 
      context: service
      dockerfile: Dockerfile
    container_name: fastapi_compose
    restart: always
    environment:
      DB_CONN: ${DB_CONN}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network_compose
  
networks:
  my_network_compose:
    driver: bridge